secretGenerator:
- name: mysql-pass
  literals:
  - password=admin
resources:
- metallb-configmap.yaml
- nginx.yaml
- mysql.yaml
- wordpress.yaml
- phpmyadmin.yaml
- ftps.yaml
- grafana.yaml
- influxdb.yaml
- telegraf.yaml
