apiVersion: v1
kind: Service
metadata:
  name: telegraf
  annotations:
    metallb.universe.tf/allow-shared-ip: same_ip
  labels:
    app: telegraf
spec:
  type: LoadBalancer
  selector:
    app: telegraf
  ports:
    - port: 8080
      name: http
      targetPort: 8080
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  labels:
    app: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - name: telegraf
        image: docker-telegraf
        imagePullPolicy: Never
        ports:
        - containerPort: 8080